server:
  port: 33333
spring:
  application:
    name: zuul
security:
  basic:
    enabled: true
  user:
    password: password123
    name: user
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone : http://user:password123@localhost:8761/eureka/
    register-with-eureka: true
zuul:
  routes:
    member: user/**
    member2: user2/**
  PreZuulFilter:
    pre:
      disable: false